#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
STOP=15

start_service() {
    /usr/sbin/dnsmasq --test --conf-file=/etc/vohive-https/direct-dns.conf >/dev/null 2>&1 || return 1
    procd_open_instance
    procd_set_param command /usr/sbin/dnsmasq --keep-in-foreground --conf-file=/etc/vohive-https/direct-dns.conf --pid-file=
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
