#!/bin/sh /etc/rc.common
USE_PROCD=1
START=97
STOP=16

start_service() {
    [ -f /etc/vohive-https/direct.pem ] || return 1
    /usr/sbin/haproxy -c -f /etc/vohive-https/direct-haproxy.cfg >/dev/null 2>&1 || return 1
    procd_open_instance
    procd_set_param command /usr/sbin/haproxy -db -f /etc/vohive-https/direct-haproxy.cfg
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
