import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

const phoneView = await readFile(new URL('../src/views/Phone.vue', import.meta.url), 'utf8')
const phoneCSS = await readFile(new URL('../src/styles/phone.css', import.meta.url), 'utf8')
const phoneStore = await readFile(new URL('../src/stores/phone.ts', import.meta.url), 'utf8')
const dialPad = await readFile(new URL('../src/components/PhoneDialPad.vue', import.meta.url), 'utf8')
const callBar = await readFile(new URL('../src/components/PhoneCallBar.vue', import.meta.url), 'utf8')
const contactsPanel = await readFile(new URL('../src/components/PhoneContactsPanel.vue', import.meta.url), 'utf8')
const contactsDrawer = await readFile(new URL('../src/components/PhoneContactsDrawer.vue', import.meta.url), 'utf8')
const contactImporter = await readFile(new URL('../src/composables/useContactImport.ts', import.meta.url), 'utf8')
const contactService = await readFile(new URL('../src/services/phone-contacts.ts', import.meta.url), 'utf8')
const phoneIdentity = await readFile(new URL('../src/composables/usePhoneIdentity.ts', import.meta.url), 'utf8')
const shell = await readFile(new URL('../src/layouts/AuthenticatedShell.vue', import.meta.url), 'utf8')
const router = await readFile(new URL('../src/router/index.ts', import.meta.url), 'utf8')
const zhCN = await readFile(new URL('../src/i18n/zh-CN.ts', import.meta.url), 'utf8')

test('phone route and navigation remain available outside the phone page', () => {
  assert.match(router, /path: '\/phone'/)
  assert.match(shell, /<PhoneCallBar\s*\/>/)
  assert.match(shell, /index: '\/phone', label: '通话中心'/)
  assert.match(zhCN, /phone:\s*'电话'/)
  assert.match(shell, /v-for="item in menuItems"/)
})

test('dial pad is an explicit fixed 3 by 4 control with accessible buttons', () => {
  assert.match(dialPad, /grid-template-columns: repeat\(3, 1fr\)/)
  assert.match(dialPad, /width: 276px/)
  assert.match(dialPad, /height: 62px/)
  assert.match(dialPad, /:aria-label=/)
  for (const digit of ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '*', '#']) {
    assert.match(dialPad, new RegExp(`digit: '${digit.replace('*', '\\*')}'`))
  }
})

test('phone view exposes explicit listen-only and microphone call actions without hiding the limitation', () => {
  assert.match(phoneView, /麦克风需要受信任的 HTTPS/)
  assert.match(phoneView, /当前 HTTP 页面可“仅听接听”或“仅听呼叫”/)
  assert.match(phoneView, /Nginx、Caddy 或其他受信任 HTTPS 地址/)
  assert.doesNotMatch(phoneView, /DEFAULT_HTTPS_PORT|打开默认 HTTPS/)
  assert.match(phoneView, />拒接</)
  assert.match(phoneView, />仅听接听</)
  assert.match(phoneView, />麦克风接听</)
  assert.match(phoneView, /@click="startListenOnlyCall"/)
  assert.match(phoneView, /@click="startTwoWayCall"/)
  assert.match(phoneView, /'正在呼叫…' : '仅听呼叫'/)
  assert.match(phoneView, /'正在呼叫…' : '双向呼叫'/)
  assert.match(phoneView, /当前页面只能仅听呼叫，对方听不到你/)
  assert.match(phoneView, /对方听不到你/)
  assert.match(phoneView, /@click="answerListenOnly\(call\)"/)
  assert.match(phoneView, /@click="enableListenOnlyMedia"/)
  assert.match(phoneStore, /answerListenOnly\(call: PhoneCall\)/)
  assert.match(phoneStore, /startListenOnlyCall\(deviceId: string, callee: string\)/)
  assert.match(phoneStore, /startCallWithMode\(deviceId, callee, 'listen-only'\)/)
  assert.match(phoneStore, /prepare\(\{ microphone: false \}\)/)
  assert.match(phoneStore, /mediaMode = 'listen-only'/)
  assert.match(phoneView, /取消静音/)
  assert.match(phoneView, /call\.held \? '恢复' : '保持'/)
  assert.match(phoneView, /第二路来电/)
  assert.match(callBar, /第二路/)
  assert.match(phoneView, /@click="toggleHold"/)
  assert.match(callBar, /保持通话/)
  assert.match(phoneView, />键盘</)
  assert.match(phoneView, /@click="hangup\(call\)"/)
  assert.match(phoneView, /'挂断中…' : '挂断'/)
  assert.match(phoneView, /sendDTMF\(digit\)/)
  assert.match(phoneView, /<PhoneCallHistory/)
  assert.match(callBar, /aria-live="polite"/)
  assert.match(callBar, /打开拨号键盘/)
  assert.match(callBar, /<PhoneDialPad/)
  assert.match(callBar, /toggleKeypad/)
  assert.doesNotMatch(callBar, /aria-label="返回电话页"/)
})

test('hangup feedback stays pending until the real call-ended event arrives', () => {
  assert.match(phoneStore, /endingCallIds: string\[\]/)
  assert.match(phoneStore, /isCallEnding\(state\)/)
  assert.match(phoneStore, /await phoneService\.hangup\(target\.call_id, this\.lease\)/)
  assert.match(phoneStore, /this\.clearEndingCall\(target\.call_id\)/)
  assert.match(phoneStore, /if \(event\.id === this\.lastEventId\) return/)
  assert.match(phoneStore, /onError:[\s\S]*void this\.refresh\(\)/)
  assert.doesNotMatch(phoneStore, /event\.id <= this\.lastEventId/)
  assert.match(phoneStore, /event\.type === 'call_ended'[\s\S]*this\.clearEndingCall\(event\.call\.call_id\)/)
  assert.match(phoneView, /phoneCallStatusLabel\(call, callEnding\)/)
  assert.match(phoneView, /已发送挂断请求/)
  assert.match(callBar, /phoneCallStatusLabel\(call, callEnding\)/)
  assert.match(callBar, /正在挂断电话/)
})

test('phone device picker uses the themed select without changing availability rules', () => {
  assert.doesNotMatch(phoneView, /<select\b/)
  assert.match(phoneView, /<el-select[\s\S]*v-model="selectedDevice"/)
  assert.match(phoneView, /<label for="phone-device">语音设备<\/label>/)
  assert.match(phoneView, /id="phone-device"[\s\S]*aria-label="语音设备"/)
  assert.match(phoneView, /:disabled="!!call"/)
  assert.match(phoneView, /<el-option v-if="!phone\.devices\.length" label="无可用设备" value=""/)
  assert.match(phoneView, /:disabled="isDeviceBusy\(device\)"/)
  assert.doesNotMatch(phoneCSS, /\.device-selector select/)
  assert.match(phoneCSS, /\.device-selector :deep\(\.el-select__wrapper\) \{ min-height: 44px;/)
})

test('phone layout has responsive single-column and 44px touch targets', () => {
  assert.match(phoneCSS, /@media \(max-width: 900px\)[\s\S]*grid-template-columns: 1fr/)
  assert.match(phoneCSS, /min-height: 48px/)
  assert.match(phoneCSS, /\.call-mode-actions \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(callBar, /width: 44px; height: 44px/)
  assert.match(shell, /<el-drawer/); assert.match(shell, /max-width: 767px/)
})

test('phone identities stay scoped to the device region and invalidate every cached alias', () => {
  assert.match(contactService, /device_id: deviceId \|\| undefined/)
  assert.match(phoneView, /identities\.resolve\(record\.peer, record\.device_id\)/)
  assert.match(phoneView, /<PhoneContactsPanel :device-id="selectedDevice"/)
  assert.match(phoneIdentity, /if \(value\.number === ident\.number\) cache\.set\(key, ident\)/)
  assert.match(phoneIdentity, /if \(drop\.has\(value\.number\)\) cache\.set\(alias, withoutContactName\(value\)\)/)
  assert.match(phoneIdentity, /revision === cacheRevision/)
})

test('contact loading failures remain visible and retryable', () => {
  assert.match(phoneIdentity, /contactsState\.error = errorMessage\(error\)/)
  assert.match(contactsDrawer, /v-if="identities\.contactsError"/)
  assert.match(contactsDrawer, /aria-label="重新加载联系人"/)
  assert.match(contactsDrawer, /v-if="identities\.contactsLoading/)
  assert.match(contactsDrawer, /v-else-if="groupedContacts\.length"/)
})

test('contact drawer resets drafts, locks background scrolling, and keeps touch targets usable', () => {
  assert.match(contactsDrawer, /function resetDraft\(\)[\s\S]*draftName\.value = ''[\s\S]*draftNumber\.value = ''/)
  assert.match(contactsDrawer, /if \(!open\) \{[\s\S]*closeAddForm\(\)/)
  assert.match(contactsDrawer, /if \(adding\.value\) \{[\s\S]*closeAddForm\(\)/)
  assert.doesNotMatch(contactsDrawer, /:lock-scroll="false"/)
  assert.match(contactsDrawer, /\.picker-add-toggle \{[\s\S]*min-height: 44px/)
  assert.match(contactsDrawer, /\.icon-button \{ width: 44px; height: 44px; flex: 0 0 44px;/)
  assert.match(contactsDrawer, /\.picker-action \{[\s\S]*min-height: 44px/)
})

test('contact management stays compact and message boxes render above the drawer', () => {
  assert.match(contactsDrawer, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(contactsDrawer, /modalClass: 'phone-contact-message-overlay'/)
  assert.match(contactsDrawer, /phone-contact-message-overlay\.el-overlay\) \{ z-index: 5200 !important;/)
  assert.doesNotMatch(contactsDrawer, /class="picker-drop"/)
  assert.match(contactsDrawer, /v-show="dropActive" class="picker-drop-overlay"/)
})

test('contacts load on scroll and keep drag import discoverable', () => {
  assert.match(contactService, /listPage\(params: PhoneContactsPageParams\)/)
  assert.match(phoneIdentity, /listPage\(\{ limit: CONTACT_PAGE_SIZE, offset \}\)/)
  assert.match(phoneIdentity, /generation !== contactsGeneration \|\| revision === cacheRevision/)
  assert.match(phoneIdentity, /function loadMoreContacts\(\)/)
  assert.match(phoneIdentity, /while \(contactsState\.hasMore\) await loadMoreContacts\(\)/)
  assert.match(contactsDrawer, /@scroll\.passive="onContactScroll"/)
  assert.match(contactsDrawer, /async function toggleSelectAll\(\)[\s\S]*await identities\.loadAllContacts\(\)/)
  assert.match(contactsDrawer, /继续向下滚动加载更多/)
  assert.match(contactsDrawer, /支持将 vcf \/ csv 拖到此处导入/)
  assert.match(contactsPanel, /identities\.contactsTotal/)
  assert.match(phoneIdentity, /if \(!page\.hasMore\) reconcileContactNameCache\(page\.contacts\)/)
  assert.match(phoneIdentity, /appendContactRows\([\s\S]*reconcileContactNameCache\(contacts\)/)
  assert.match(phoneIdentity, /function removeLocalContacts\([\s\S]*contactsGeneration\+\+[\s\S]*cacheRevision\+\+/)
})

test('contact import behavior is shared and exposes list refresh failures', () => {
  assert.match(contactsPanel, /useContactImport\(/)
  assert.match(contactsDrawer, /useContactImport\(/)
  assert.match(contactImporter, /但列表刷新失败/)
  assert.match(contactImporter, /input\.value = ''/)
  assert.match(contactImporter, /reloadContacts\(\{ fresh: true \}\)/)
  assert.match(phoneIdentity, /if \(contactsLoadPromise && !options\.fresh\) return contactsLoadPromise/)
  assert.match(contactsDrawer, /:disabled="exporting"/)
  assert.match(contactsDrawer, /exporting\.value = false/)
})

test('contacts are grouped by persistent identity instead of display name', () => {
  assert.match(contactService, /contact_id\?: string/)
  assert.match(contactsDrawer, /return item\.contact_id \|\| `number:\$\{item\.number\}`/)
  assert.match(contactsDrawer, /contactId = contactGroupID\(group\)/)
  assert.match(contactService, /async saveMany\([\s\S]*\/phone\/contacts\/batch/)
  assert.match(contactService, /atomic: true/)
  assert.match(contactsDrawer, /saveMany\(numbers\.map/)
  assert.match(contactService, /async updateGroup\([\s\S]*\/phone\/contacts\/group/)
  assert.match(contactService, /async removeGroup\([\s\S]*\/phone\/contacts\/group/)
  assert.match(contactsDrawer, /updateGroup\(contactId, name\)/)
  assert.match(contactsDrawer, /removeContactGroup\(contactId\)/)
  assert.doesNotMatch(contactsDrawer, /index\.get\(name\)/)
})

test('wifi calling keeps a dedicated start switch under the mode control', () => {
  assert.match(phoneView, /async function toggleWifiCalling/)
  assert.match(phoneView, /v-show="selectedMode === 'wifi'"/)
  assert.match(phoneView, /class="phone-wifi-calling-switch"/)
  assert.match(phoneView, /disableVoWiFi\(selectedDevice\.value\)/)
  assert.match(phoneView, /打开后开始注册。关掉只停服务，仍是 WiFi calling/)
  assert.match(phoneView, /if \(mode === selectedMode\.value\) \{[\s\S]*if \(mode === 'wifi'\) return/)
  assert.match(phoneView, /:disabled="!!call \|\| modePending \|\| lebaraIdentityBusy\(selected\)"/)
  assert.doesNotMatch(phoneView, /modePending \|\| !!selected\?\.rf_lock/)
  assert.match(phoneView, /status === 'recovering' \|\| status === 'waiting_identity'/)
  assert.match(phoneView, /正在恢复英国身份/)
  assert.match(phoneView, /retryLebaraIdentity/)
  assert.match(phoneView, /lebara_identity_iccid/)
  assert.doesNotMatch(phoneView, /点 WiFi calling 即可拉起/)
  assert.match(phoneCSS, /\.phone-wifi-calling-switch \{[\s\S]*min-height: 44px/)
})
