#!/bin/sh /etc/rc.common
START=99
STOP=15
USE_PROCD=1
start_service() {
    procd_open_instance
    procd_set_param command /etc/qiyou-passwall-compat-monitor.sh
    procd_set_param respawn 3600 5 5
    procd_close_instance
}
