name: hideck-runtime-image

services:
  hideck-runtime:
    image: yibaiba/hideck-runtime:3.24
    build:
      context: .
      dockerfile: Dockerfile.runtime
      pull: true
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - yibaiba/hideck-runtime:latest
      provenance: false
      sbom: false
